# Generated by Django 4.2 on 2023-04-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categoryThrough',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post',
        ),
    ]
